bruh9000-changes-1
moddio/moddio-docs pull request #18
Opened 2023-11-10 01:58 UTC by bruh-9000

Increased amount of descriptions for the Modd.io Docs.

2023-11-13 18:12 UTC, sloont requested changes

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/addChatFilter.md
great.

maybe add example of comma-separated list

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/allItemsDroppedOnGround.md
pretty sure `allItemsDroppedOnGround` isn't a loop script action. It should be a script variable with a data type of `itemGroup`

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/botPlayers.md
bot players is a variable of data type `playerGroup` and not a loop script action

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/changeInventorySlotColor.md
i thought this didn't change color if in backpack

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/changeItemInventoryImage.md
does this even work? how do you provide an image?

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/closeDialogueForPlayer
"that have text, and can have images too." >> "that can have text and images."

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/closeDialogueForPlayer
> +Dialogues are popups shown to a player that have text, and can have images too. Dialogues can be affected by HTML and other code for custom formatting. Each dialogue also has the options for buttons
"options" >> "option"

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/comment.md
"in the game editor" >> "in the script editor"
"Write anything here" >> "Write here"

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/createFloatingText.md
"in the color selected." >> "in the provided color"
"The text will slowly float" >> "The text will float"
"You also cannot change the duration of the text, nor the font. >> "You cannot change the duration, text, or font."

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/dropAllItems.md
"onto" >> "on"

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/getItemMaxQuantity.md
this is not "in the form of an integer". it *is* an integer.

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/getItemQuantity.md
same as max
this is not "in the form of an integer". it *is* an integer.

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/giveNewItemToUnit.md
"have the default item qualities that the item has." >> "have the default properties of the item type."

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/giveNewItemWithQuantityToUnit.md
same as give new item
"have the default item qualities that the item has." >> "have the default properties of the item type."

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/giveNewItemWithQuantityToUnit.md
> +Gives the specified item to the provided unit. The item will have the default item qualities that the item has, besides the item quantity. The item quantity will be set to the provided amount.
probably should specify provided quantity expects an integer

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/humanPlayers.md
not a loop script action. script variable of data type `playerGroup`

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/increaseVariableByNumber.md
maybe these modify variable by number actions should specify that the variable has to be a data type `Number`

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/makePlayerTradeWithPlayer.md
i'd rather this just say "removed" or just not include this file at all.

eventually we would want a placeholder link to contribute to moddio2 repo but that's a different task and is outside of the scope of these edits.

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/openDialogueForPlayer.md
for the overview, i like the "specified, provided" syntax you used in above descriptions

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/openDialogueForPlayer.md
> +Dialogues are popups shown to a player that have text, and can have images too. Dialogues can be affected by HTML and other code for custom formatting. Each dialogue also has the options for buttons
should copy the majority of the changes suggested for the earlier dialogue action. For the new part, you can just say "Dialogues can contain HTML."

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/openShopForPlayer.md
"specified player." >> "provided player."

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/openWebsiteForPlayer.md
swap provided, specified?

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/playAdForPlayer.md
"selected player" >> "provided player"

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/playMusicForPlayer,md
"specified player" >> "provided player"

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/playMusicForPlayerRepeatedly.md
"specified player" >> "provided player"

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/playSoundAtPosition.md
"specified location" >> "provided location"
"specific sound" >> "unique sound"

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/playSoundForPlayer.md
"specified player" >> "provided player"

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/playerTypeOfPlayer.md
"which player type the selected player is on." >> "the player type of the provided player."

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/selectedPlayer.md
"When looping through players it" >> "When looping through players, it"

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/sendChatMessageToPlayer.md
"specifically" >> none
"selected" >> "provided"

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/setEntityAttribute.md
"whatever value is inputted" >> "the provided value"
"Attributes can only be numbers." >> "This value must be a number."

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/setEntityAttributeMax.md
"selected attribute" >> "specified attribute"
"selected entity to the inputted number." >> "provided entity. This value must be a number."

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/setEntityAttributeMin.md
"selected attribute" >> "specified attribute"
"selected entity to the inputted number." >> "provided entity. This value must be a number."

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/setEntityState.md
"selected" >> "specified"

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/setItemFireRate.md
"Changes the fire rate of the specified item to the provided time. This value is in milliseconds and must be an integer."

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/setItemName.md
"input" >> "string"

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/showUnitInPlayerMinimap.md
same comment as the make players trade action. 

either "removed" or just don't include the file.

deprecated not depreciated, but also deprecated implies that it still exists and can be used

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/spawnItem.md
"location provided" >> "provided location"

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/startUsingItem.md
"unit" >> "specified unit"
"item" >> "provided item"

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/stopMusicForPlayer.md
"any song" >> "music"
"specified" >> "provided"
"player isn't currently listening to music," >> "player's game isn't playing music,"

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/stopSoundForPlayer.md
"specified player" >> "provided player"

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/stopUsingItem.md
"unit" >> "specified unit"
"specified item" >> "provided item"

2023-11-13 18:12 UTC, sloont commented on scripting-reference/actions/unbanPlayerFromChat.md
"ingame" >> "in-game"

2023-11-13 18:12 UTC, sloont commented on scripting-reference/triggers/coinSendFailureDueToDailyLimit.md
for the overview there's an important distinction between the owner sending out too many coins and the game sending out too many coins. this trigger is for when the game sends out too many coins

2023-11-13 18:12 UTC, sloont commented on scripting-reference/triggers/coinSendFailureDueToDailyLimit.md
> +Game owners who are sending out coins can set a maximium limit to how many coins can be sent out each real life day. Every day, this number resets. All Modd Coins sent out by the game will contribute
"can be sent out each real life day." >> "can be transferred each day."
"Every day, this number resets." >> Remove as its implied by the previous sentence.
"coins are attempted to be given to a player." >> "the game attempts to give coins to a player."

2023-11-13 18:12 UTC, sloont commented on scripting-reference/triggers/coinSendFailureDueToInsufficientCoins
split into two sentences: 
"balance. They cannot give"

2023-11-13 18:12 UTC, sloont commented on scripting-reference/triggers/entityAStarPathFindingFailed.md
"a unit" >> "an AI unit"
split into two sentences:
"but fails. Failure is most often due to"

2023-11-13 18:12 UTC, sloont commented on scripting-reference/variables/absoluteValueOfNumber.md
"Uses the absolute value function on the provided input and returns the output." >> "Returns the absolute value of the provided number."

2023-11-13 18:12 UTC, sloont commented on scripting-reference/variables/currentTimeStamp.md
> +Creating a script that allows players to claim rewards for joining the game daily, but only once a day
missing .

2023-11-13 18:12 UTC, sloont commented on scripting-reference/variables/getHeightOfRegion.md
"region's" >> "specified region"

2023-11-13 18:12 UTC, sloont commented on scripting-reference/variables/getMapTileId.md
", for an" >> ", an"
" unit is in, for example. Each" >> " unit is at. For example: each"
"which goes by tile width" >> "which goes by pixels"

2023-11-13 18:12 UTC, sloont commented on scripting-reference/variables/getRandomNumberBetween.md
are the two numbers inclusive or exclusive?

2023-11-13 18:12 UTC, sloont commented on scripting-reference/variables/mathFloor.md
"int" >> "integer"
can probably remove "(whole number)"

2023-11-13 18:12 UTC, sloont commented on scripting-reference/variables/selectedItem.md
"Returns the item that is selected at the current iteration of the loop"

2023-11-13 18:12 UTC, sloont commented on workspaces/map-editor.md
remove this file. outside of the scope of this PR. not sure i love the content either.

2023-11-14 03:07 UTC, bruh-9000 commented on scripting-reference/actions/openDialogueForPlayer.md
Thanks :D

2023-11-14 03:08 UTC, bruh-9000 commented on scripting-reference/actions/openDialogueForPlayer.md
> +Dialogues are popups shown to a player that have text, and can have images too. Dialogues can be affected by HTML and other code for custom formatting. Each dialogue also has the options for buttons
I don't understand

2023-11-14 03:31 UTC, bruh-9000 commented on scripting-reference/actions/changeInventorySlotColor.md
no it works in the backpack i just checked

2023-11-30 00:39 UTC, sloont requested changes

2023-11-30 00:39 UTC, sloont commented on scripting-reference/actions/allItemsDroppedOnGround.md
this explains nothing about this script variable or what it is used for

2023-11-30 00:39 UTC, sloont commented on scripting-reference/actions/botPlayers.md
this is true but it has nothing to do with explaining the variable

2023-11-30 00:39 UTC, sloont commented on scripting-reference/actions/break.md
incomplete sentence

2023-11-30 00:39 UTC, sloont commented on scripting-reference/actions/condition.md
seems a bit confusing. i would just say something like 'if the expression evaluates to true'

2023-11-30 00:39 UTC, sloont commented on scripting-reference/actions/createFloatingText.md
i think you can combine these two sections into a few sentences instead of having overview&usage

2023-11-30 00:39 UTC, sloont commented on scripting-reference/actions/humanPlayers.md
again, this says nothing about what the actual variable is doing --like the description for botPlayers

2023-11-30 00:39 UTC, sloont commented on scripting-reference/actions/openDialogueForPlayer.md
> +Dialogues are popups shown to a player that have text, and can have images too. Dialogues can be affected by HTML and other code for custom formatting. Each dialogue also has the options for buttons
remove second sentence in ##what are dialogues

2023-11-30 02:27 UTC, sloont approved these changes

2023-11-30 02:27 UTC, merged